@host = http://localhost:3001
@route = /api/note

### GET ALL
GET {{host}}{{route}}
?search=changed
&index=0
&limit=5

### GET ONE
GET {{host}}{{route}}/4 HTTP/1.1

### CREATE
POST {{host}}{{route}} HTTP/1.1
content-type: application/json

{
  "title": "sample",
  "body": "testing"
}

#### UPDATE
PUT {{host}}{{route}} HTTP/1.1
content-type: application/json

{
  "id": 1,
  "title": "changed",
  "body": "changing"
}

### DELETE
DELETE {{host}}{{route}} HTTP/1.1
content-type: application/json

{
  "id": 3
}
